# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-16.04
  container:
      image: pdal/azp-dependencies:latest
      options: --privileged
  timeoutInMinutes: 60
  steps:
  - script: |
      echo "current directory:" `pwd`
      mkdir build
      cd build
      cmake .. \
        -G Ninja \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBUILD_PLUGIN_PYTHON=ON \
        -DBUILD_PLUGIN_CPD=ON \
        -DCMAKE_INSTALL_PREFIX=`pwd`/../install \
        -DBUILD_PLUGIN_I3S=ON \
        -DBUILD_PLUGIN_NITF=ON \
        -DBUILD_PLUGIN_ICEBRIDGE=ON \
        -DBUILD_PLUGIN_PGPOINTCLOUD=ON \
        -DBUILD_PLUGIN_SQLITE=OFF \
        -DBUILD_PLUGIN_E57=ON \
        -DBUILD_PGPOINTCLOUD_TESTS=OFF \
        -DBUILD_SQLITE_TESTS=OFF \
        -DPYTHON_EXECUTABLE=/usr/bin/python3 \
        -DPython3_FIND_STRATEGY=LOCATION \
        -DBUILD_PLUGIN_SQLITE=ON \
        -DWITH_LAZPERF=ON \
        -DWITH_LASZIP=ON \
        -DWITH_ZSTD=ON \
        -DWITH_ZLIB=ON \
        -DWITH_TESTS=ON
    displayName: 'CMake'
  - script: |
      cd build
      ninja
    displayName: 'Build'
  - script: |
      cd build
      ctest -V
    displayName: 'Test'
  - script: |
      export PDAL_TEST_DIR=`pwd`/test
      export INSTALL_DIR=`pwd`/install
      export PATH=$PATH:$INSTALL_DIR/bin
      cd build
      ls build/lib/*
      ninja install
      # Python extension testing
      #
      pip3 install packaging cython
      git clone https://github.com/PDAL/python.git pdal-python
      cd pdal-python
      git checkout 2.0.0
      python3 setup.py build
      LD_LIBRARY_PATH=$INSTALL_DIR/lib python3 setup.py test
    displayName: 'Python'
  - script: |
      export BASE=`pwd`
      for EXAMPLE in writing writing-filter writing-kernel writing-reader writing-writer
      do
          cd $BASE/examples/$EXAMPLE
          mkdir -p _build || exit 1
          cd _build || exit 1
          cmake -G "Ninja" .. -DPDAL_DIR=$BASE/install/lib/cmake/PDAL && ninja
      done
    displayName: 'Examples'

