# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_build:
      # - doxygen ./doc/doxygen/doxygen.conf 1> /dev/null
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx book/"
      - sed -i '1i\ import os, sys; sys.path.append(os.path.abspath("./_ext"))' book/conf.py

  # apt_packages:
  #   - graphviz

sphinx:
  # builder: html
  configuration: book/conf.py
  # fail_on_warning: true

# python:
#   install:
#     - requirements: book/requirements.txt

conda:
  environment: book/environment.yml

formats: all
