# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"
  jobs:
    pre_build:
      - ./doc/rtd-prebuild.sh
    build:
      html:
        - jupyter-book build doc/
        - cp -R doc/_build/html/* $READTHEDOCS_OUTPUT/html
      # not sure how this compares to --builder=latex + latexmk (rtd default)
      pdf:
        - jupyter-book build --builder pdflatex doc/
        - cp -R doc/_build/latex/* $READTHEDOCS_OUTPUT/pdf
      htmlzip:
        - jupyter-book build --builder singlehtml doc/
        - cp -R doc/_build/singlehtml/* $READTHEDOCS_OUTPUT/htmlzip
      epub:
        - jupyter-book build --builder custom --custom-builder epub doc/
        - cp -R doc/_build/epub/* $READTHEDOCS_OUTPUT/epub
  apt_packages:
    - graphviz

sphinx:
  # builder: html
  configuration: doc/conf.py
  # fail_on_warning: true

conda:
  environment: doc/environment.yml

formats: all
