del /s /q build
mkdir build
cd build

set CONDA_ROOT=c:\users\hobu\miniconda3
set ORACLE_HOME=%CONDA_ROOT%
cmake -G "NMake Makefiles" ^
      -DCMAKE_INSTALL_PREFIX:PATH="%CONDA_ROOT%" ^
      -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo ^
      -DCMAKE_LIBRARY_PATH:FILEPATH="=%CONDA_ROOT%/Library/lib" ^
      -DCMAKE_INCLUDE_PATH:FILEPATH="%CONDA_ROOT%/Library/include" ^
      -DBUILD_PLUGIN_GREYHOUND=ON ^
      -DBUILD_PLUGIN_PCL=ON ^
      -DBUILD_PLUGIN_PYTHON=ON ^
      -DBUILD_PLUGIN_PGPOINTCLOUD=ON ^
      -DBUILD_PLUGIN_OCI=ON ^
      -DBUILD_PLUGIN_I3S=ON ^
      -DBUILD_PLUGIN_SQLITE=ON ^
      -DBUILD_PLUGIN_ICEBRIDGE=ON ^
      -DBUILD_PLUGIN_HEXBIN=ON ^
      -DBUILD_PLUGIN_NITF=ON ^
      -DENABLE_CTEST=OFF ^
      -DWITH_TESTS=ON ^
	-DORACLE_INCLUDE_DIR=%CONDA_ROOT%/include ^
	-DORACLE_LIBRARY=%CONDA_ROOT%/libs/oci.lib ^
    -DLazperf_DIR=%CONDA_ROOT%/Library/cmake ^
    -DHDF5_DIR=%CONDA_ROOT%/Library/cmake ^
    -DPCL_DIR=%CONDA_ROOT%/Library/cmake ^
    -DWITH_ZLIB=ON ^
    -DBUILD_PGPOINTCLOUD_TESTS=OFF ^
    -DBUILD_SQLITE_TESTS=OFF ^
    -DBUILD_OCI_TESTS=OFF ^
    -DCMAKE_VERBOSE_MAKEFILE=OFF ^
      -DWITH_LAZPERF=ON ^
      -DWITH_LASZIP=ON ^
      .. --debug-trycompile
