#!/bin/bash -e
# Builds and tests PDAL
source ./scripts/ci/common.sh
mkdir -p _build || exit 1
cd _build || exit 1

case "$PDAL_OPTIONAL_COMPONENTS" in
    all)
        OPTIONAL_COMPONENT_SWITCH=ON
        ;;
    none)
        OPTIONAL_COMPONENT_SWITCH=OFF
        ;;
    *)
        echo "Unrecognized value for PDAL_OPTIONAL_COMPONENTS=$PDAL_OPTIONAL_COMPONENTS"
        exit 1
esac

cmake \
    -DWITH_APPS=ON \
    -DWITH_TESTS=ON \
    -DWITH_PKGCONFIG=ON \
    -DWITH_GDAL=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_GEOTIFF=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_ORACLE=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_ICONV=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_LASZIP=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_LIBXML2=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_MSGPACK=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_NITRO=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_PGPOINTCLOUD=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_PYTHON=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_ZLIB=$OPTIONAL_COMPONENT_SWITCH \
    -DWITH_CARIS=OFF \
    -DWITH_SQLITE=OFF \
    -DENABLE_CTEST=OFF \
    -DPDAL_EMBED_BOOST=OFF \
    -DWITH_HDF5=OFF \
    ..

make -j ${NUMTHREADS}

ctest -V --output-on-failure .
