channels:
  - conda-forge
dependencies:
  - python-pdal
  - proj
  - pip
  - pip:
    - jupyter-book
    - breathe
    - sphinx > 6
    - sphinxcontrib-jquery
    - sphinxcontrib-bibtex
    - sphinx-notfound-page
    - sphinx-inline-tabs
