channels:
  - conda-forge
dependencies:
  - doxygen
  - make
  - python-pdal
  - jupyter-book
  - breathe > 4.34
  - sphinxcontrib-jquery
  - sphinx-notfound-page
  - sphinx-inline-tabs
  - cmake
  - pillow
  - sphinx-jupyterbook-latex
  - imagemagick
  - compilers


