/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azavea_pdal_PointViewIterator */

#ifndef _Included_com_azavea_pdal_PointViewIterator
#define _Included_com_azavea_pdal_PointViewIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azavea_pdal_PointViewIterator
 * Method:    hasNext
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_azavea_pdal_PointViewIterator_hasNext
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointViewIterator
 * Method:    next
 * Signature: ()Lcom/azavea/pdal/PointView;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_PointViewIterator_next
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointViewIterator
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_PointViewIterator_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
