/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pdal_PointView */

#ifndef _Included_io_pdal_PointView
#define _Included_io_pdal_PointView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pdal_PointView
 * Method:    layout
 * Signature: ()Lio/pdal/PointLayout;
 */
JNIEXPORT jobject JNICALL Java_io_pdal_PointView_layout
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_PointView
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_pdal_PointView_size
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_PointView
 * Method:    empty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_pdal_PointView_empty
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_PointView
 * Method:    getCrsProj4
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsProj4
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_PointView
 * Method:    getCrsWKT
 * Signature: (IZ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_pdal_PointView_getCrsWKT
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_pdal_PointView
 * Method:    getPackedPoint
 * Signature: (J[Lio/pdal/DimType;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoint
  (JNIEnv *, jobject, jlong, jobjectArray);

/*
 * Class:     io_pdal_PointView
 * Method:    getPackedPoints
 * Signature: ([Lio/pdal/DimType;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pdal_PointView_getPackedPoints
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     io_pdal_PointView
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_PointView_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
