/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pdal_Pipeline */

#ifndef _Included_io_pdal_Pipeline
#define _Included_io_pdal_Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pdal_Pipeline
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_initialise
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    execute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_execute
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    getPointViews
 * Signature: ()Lio/pdal/PointViewIterator;
 */
JNIEXPORT jobject JNICALL Java_io_pdal_Pipeline_getPointViews
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_dispose
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    getMetadata
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getMetadata
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    getSchema
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getSchema
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    validate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_io_pdal_Pipeline_validate
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    setLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_pdal_Pipeline_setLogLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_pdal_Pipeline
 * Method:    getLogLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_pdal_Pipeline_getLogLevel
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_Pipeline
 * Method:    getLog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_pdal_Pipeline_getLog
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
