/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pdal_PointLayout */

#ifndef _Included_io_pdal_PointLayout
#define _Included_io_pdal_PointLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pdal_PointLayout
 * Method:    dimTypes
 * Signature: ()[Lio/pdal/DimType;
 */
JNIEXPORT jobjectArray JNICALL Java_io_pdal_PointLayout_dimTypes
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_PointLayout
 * Method:    findDimType
 * Signature: (Ljava/lang/String;)Lio/pdal/DimType;
 */
JNIEXPORT jobject JNICALL Java_io_pdal_PointLayout_findDimType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_pdal_PointLayout
 * Method:    dimSize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimSize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_pdal_PointLayout
 * Method:    dimPackedOffset
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_dimPackedOffset
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_pdal_PointLayout
 * Method:    pointSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_io_pdal_PointLayout_pointSize
  (JNIEnv *, jobject);

/*
 * Class:     io_pdal_PointLayout
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_pdal_PointLayout_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
