/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azavea_pdal_PointLayout */

#ifndef _Included_com_azavea_pdal_PointLayout
#define _Included_com_azavea_pdal_PointLayout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azavea_pdal_PointLayout
 * Method:    dimTypes
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_PointLayout_dimTypes
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointLayout
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_PointLayout_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
