/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azavea_pdal_PointView */

#ifndef _Included_com_azavea_pdal_PointView
#define _Included_com_azavea_pdal_PointView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azavea_pdal_PointView
 * Method:    points
 * Signature: ()Lscala/collection/Iterable;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_PointView_points
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
