/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azavea_pdal_PointView */

#ifndef _Included_com_azavea_pdal_PointView
#define _Included_com_azavea_pdal_PointView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azavea_pdal_PointView
 * Method:    layout
 * Signature: ()Lcom/azavea/pdal/PointLayout;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_PointView_layout
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointView
 * Method:    size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_azavea_pdal_PointView_size
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointView
 * Method:    empty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_azavea_pdal_PointView_empty
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointView
 * Method:    getPackedPoint
 * Signature: (Ljava/util/List;J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_azavea_pdal_PointView_getPackedPoint
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     com_azavea_pdal_PointView
 * Method:    getPackedPoints
 * Signature: (Ljava/util/List;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_azavea_pdal_PointView_getPackedPoints
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_azavea_pdal_PointView
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_PointView_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_PointView
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_PointView_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
