/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azavea_pdal_PointViewIterator */

#ifndef _Included_com_azavea_pdal_PointViewIterator
#define _Included_com_azavea_pdal_PointViewIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azavea_pdal_PointViewIterator
 * Method:    layout
 * Signature: ()Lcom/azavea/pdal/PointLayout;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_PointViewIterator_layout
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
