/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_azavea_pdal_Pipeline */

#ifndef _Included_com_azavea_pdal_Pipeline
#define _Included_com_azavea_pdal_Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_Pipeline_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    execute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_Pipeline_execute
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    pointViews
 * Signature: ()Lcom/azavea/pdal/PointViewIterator;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_Pipeline_pointViews__
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    pointViews
 * Signature: (Lcom/azavea/pdal/PointLayout;)Lcom/azavea/pdal/PointViewIterator;
 */
JNIEXPORT jobject JNICALL Java_com_azavea_pdal_Pipeline_pointViews__Lcom_azavea_pdal_PointLayout_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    test
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_azavea_pdal_Pipeline_test
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_Pipeline_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    getMetadata
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_azavea_pdal_Pipeline_getMetadata
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    getSchema
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_azavea_pdal_Pipeline_getSchema
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    validate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_azavea_pdal_Pipeline_validate
  (JNIEnv *, jobject);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    setLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_azavea_pdal_Pipeline_setLogLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_azavea_pdal_Pipeline
 * Method:    getLogLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_azavea_pdal_Pipeline_getLogLevel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
