if(NOT ROOT_DIR)
    message(FATAL_ERROR "ROOT_DIR must be set in top-level CMakeLists.txt")
endif()
set(PDAL_SRC_DIR ${ROOT_DIR}/pdal)
set(PDAL_INCLUDE_DIR ${ROOT_DIR})
set(PDAL_CMAKE_DIR ${ROOT_DIR}/cmake)
set(PDAL_MODULE_DIR ${PDAL_CMAKE_DIR}/modules)
set(PDAL_UTIL_DIR ${PDAL_SRC_DIR}/util)
set(PDAL_TOOLS_DIR ${ROOT_DIR}/tools)
set(PDAL_KERNELS_DIR ${ROOT_DIR}/kernels)
set(PDAL_FILTERS_DIR ${ROOT_DIR}/filters)
set(PDAL_IO_DIR ${ROOT_DIR}/io)
set(PDAL_VENDOR_DIR ${ROOT_DIR}/vendor)

