option(WITH_LAZPERF "Build PDAL with support for LAZ compression with LAZPERF" TRUE)
if (WITH_LAZPERF)
    find_package(LAZPERF 2.0 QUIET)
    set_package_properties(LAZPERF PROPERTIES TYPE OPTIONAL)
    if (LAZPERF_FOUND)
        set(LAZPERF_LIBRARY "LAZPERF::lazperf")
        set(PDAL_HAVE_LAZPERF 1)
    else()
        set(LAZPERF_LIBRARY "")
        set(PDAL_HAVE_LAZPERF 0)
    endif()
endif()
