name: Backport
on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  contents: read

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport

    permissions:
      pull-requests: write

    # Adapt https://github.com/m-kuhn/backport
    steps:
      - name: Backport Bot
        id: backport
        if: github.event.pull_request.merged && ( ( github.event.action == 'closed' && contains( join( github.event.pull_request.labels.*.name ), 'backport') ) || contains( github.event.label.name, 'backport' ) )
        uses: m-kuhn/backport@74eb973c022c9abb04555b3fde955fbe056d78f5 # v1.2.8
        with:
          github_token: ${{ secrets.BACKPORT_TOKEN }}
