name: OSX and Linux

on:
  push:
    branches: '*'

jobs:
  build:
    name: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ['ubuntu-latest', 'macos-latest' ]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
        channels: conda-forge
        auto-update-conda: true

    - name: Setup
      shell: bash -l {0}
      run: |
          ./scripts/ci/unix/setup.sh

    - name: CMake
      shell: bash -l {0}
      run: |
          ./scripts/ci/unix/cmake.sh
      working-directory: ./build

    - name: Compile
      shell: bash -l {0}
      run: |
          ./scripts/ci/unix/compile.sh
      working-directory: ./build

    - name: Test
      shell: bash -l {0}
      run: |
          ./scripts/ci/unix/test.sh
      working-directory: ./build

    - name: Examples
      shell: bash -l {0}
      run: |
          ./scripts/ci/unix/examples.sh

