{% set name = "pdal" %}
{% set version = "master" %}
{% set sha256 = "1d88c96b9407396be22c9ebf564023feb82d65456b5666ecd50b0e7ea5f75ab0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/PDAL/PDAL.git
  git_rev: master

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - numpy
    - libgdal
    - geotiff
    - postgresql
    - libkml
    - eigen
    - sqlite
    - laz-perf
    - nitro
    - laszip
    - curl
    - zlib
    - hdf5
  run:
    - python
    - numpy
    - postgresql
    - laz-perf
    - geotiff
    - laszip
    - hdf5
    - libgdal
    - {{ pin_compatible('numpy') }}
    - nitro
    - curl
    - zlib

test:
  commands:
    - pdal --version
    - pdal --drivers --debug

about:
  home: https://www.pdal.io
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Point Data Abstraction Library (PDAL)'
  description: |
    Point cloud data processing.
  doc_url: https://www.pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - chambbj
    - hobu
